const recipes=[
{icon:'🌌',title:'Vía Láctea',desc:'Cielo nocturno y estrellas',qs:[['¿Tienes trípode?',['Sí','No']],['¿Guardarás en RAW?',['Sí','No']]],build:a=>({settings:[['Modo','Manual'],['Apertura','f/2'],['Velocidad',a[0]==='Sí'?'10 s':'3 s'],['ISO',a[0]==='Sí'?'3200':'6400'],['Enfoque','Manual']],steps:[
'Coloca la cámara en un trípode o sobre una superficie completamente estable.',
'Comprueba que el filtro ND esté desactivado.',
'Pon el dial de velocidad en T y selecciona '+(a[0]==='Sí'?'10 segundos':'3 segundos')+'.',
'Gira el anillo de apertura hasta f/2.',
'Selecciona ISO '+(a[0]==='Sí'?'3200':'6400')+'.',
'Mueve el selector frontal de enfoque a M.',
'Amplía una estrella brillante y gira el anillo de enfoque hasta verla lo más pequeña posible.',
'Selecciona calidad '+(a[1]==='Sí'?'RAW + JPEG':'JPEG')+'.',
'Activa el temporizador de 2 segundos y haz la foto.',
'Amplía la imagen. Si las estrellas dejan trazo, reduce el tiempo de exposición.'
],tip:'Para la Vía Láctea, un trípode marca una diferencia decisiva.'})},
{icon:'🌙',title:'Calle de noche',desc:'Luces urbanas y poca luz',qs:[['¿Hay personas en movimiento?',['Sí','No']],['¿Tienes trípode o apoyo?',['Sí','No']]],build:a=>{const mov=a[0]==='Sí',tri=a[1]==='Sí';return{settings:[['Modo',tri&&!mov?'Manual':'Prioridad apertura'],['Apertura',mov?'f/2':'f/2–f/4'],['Velocidad',mov?'1/125 s mínimo':tri?'1 s':'1/60 s mínimo'],['ISO',tri&&!mov?'125':'AUTO hasta 6400'],['Enfoque',mov?'AF-C':'AF-S']],steps:tri&&!mov?[
'Coloca la cámara en el trípode o apoyo estable.','Pon el dial de velocidad en T y selecciona 1 segundo.','Selecciona f/5.6.','Selecciona ISO 125.','Activa el temporizador de 2 segundos.','Enfoca, pulsa el disparador y no toques la cámara.'
]:['Pon el dial de velocidad en A.','Gira el anillo de apertura hasta '+(mov?'f/2':'f/2')+'.','Pon el dial ISO en A.','En AJUSTE ISO AUTO, selecciona ISO máximo 6400.','Selecciona una velocidad mínima de '+(mov?'1/125 s':'1/60 s')+'.','Coloca el selector de enfoque en '+(mov?'C':'S')+'.','Sujeta firmemente la cámara, enfoca y dispara.'],tip:mov?'Si las personas salen movidas, prueba 1/250 s.':'Haz dos o tres fotografías para asegurar una imagen nítida.'}}},
{icon:'🙂',title:'Retrato',desc:'Cara nítida y fondo suave',qs:[['¿La persona se mueve?',['Sí','No']],['¿Hay poca luz?',['Sí','No']]],build:a=>{const mov=a[0]==='Sí',dark=a[1]==='Sí';return{settings:[['Modo','Prioridad apertura'],['Apertura',mov?'f/2.8':'f/2'],['Velocidad mínima',mov?'1/250 s':'1/125 s'],['ISO',dark?'AUTO hasta 12800':'AUTO hasta 6400'],['Enfoque',mov?'AF-C + ojo':'AF-S + ojo']],steps:['Pon el dial de velocidad en A.','Selecciona '+(mov?'f/2.8':'f/2')+' en el anillo de apertura.','Pon ISO en A.','Configura ISO máximo '+(dark?'12800':'6400')+' y velocidad mínima '+(mov?'1/250 s':'1/125 s')+'.','Activa DETECCIÓN DE CARA/OJOS y selecciona OJO AUTO.','Coloca el selector de enfoque en '+(mov?'C':'S')+'.','Separa a la persona del fondo, enfoca al ojo más cercano y dispara.'],tip:'Es preferible algo de ruido a una cara movida.'}}},
{icon:'🏞️',title:'Paisaje',desc:'Nitidez de cerca a lejos',qs:[['¿Tienes trípode?',['Sí','No']],['¿Hay poca luz?',['Sí','No']]],build:a=>{const tri=a[0]==='Sí',dark=a[1]==='Sí';return{settings:[['Modo','Prioridad apertura'],['Apertura',tri?'f/8':'f/5.6'],['ISO',tri?'125':'AUTO'],['Velocidad mínima',tri?'Automática':dark?'1/60 s':'1/125 s'],['Temporizador',tri?'2 s':'No']],steps:['Comienza con el dial de velocidad en A.','Selecciona '+(tri?'f/8':'f/5.6')+'.','Selecciona '+(tri?'ISO 125':'ISO AUTO')+'.',...(tri?['Monta la cámara en el trípode.','Activa el temporizador de 2 segundos.']:['Sujeta la cámara con ambas manos y pega los codos al cuerpo.']),'Enfoca aproximadamente a un tercio de la profundidad de la escena.','Comprueba que el horizonte esté recto y haz la foto.'],tip:'Evita f/16 salvo que necesites un efecto concreto; puede reducir la nitidez.'}}},
{icon:'🏃',title:'Movimiento',desc:'Niños, animales y acción',qs:[['¿El movimiento es rápido?',['Sí','No']],['¿Hay poca luz?',['Sí','No']]],build:a=>{const fast=a[0]==='Sí',dark=a[1]==='Sí';const speed=fast?(dark?'1/500 s':'1/1000 s'):(dark?'1/250 s':'1/500 s');return{settings:[['Modo','Prioridad velocidad'],['Velocidad',speed],['Apertura','Automática'],['ISO',dark?'AUTO hasta 12800':'AUTO'],['Enfoque','AF-C + Zona']],steps:['Pon el anillo de apertura en A.','Selecciona '+speed+' en el dial de velocidad.','Pon ISO en A'+(dark?' con máximo 12800':'')+'.','Mueve el selector frontal de enfoque a C.','En MODO AF selecciona ZONA.','Mantén la zona sobre el sujeto mientras lo sigues.','Dispara una ráfaga corta.'],tip:'Si la imagen queda oscura, busca más luz antes de reducir mucho la velocidad.'}}},
{icon:'☀️',title:'Retrato al sol',desc:'Fondo desenfocado con mucha luz',qs:[['¿Quieres usar f/2?',['Sí','No']],['¿Usarás flash de relleno?',['Sí','No']]],build:a=>{const wide=a[0]==='Sí',flash=a[1]==='Sí';return{settings:[['Modo','Prioridad apertura'],['Apertura',wide?'f/2':'f/4'],['ISO','125'],['Filtro ND',wide?'Activado':'Según necesidad'],['Flash',flash?'Activado':'Desactivado']],steps:['Pon el dial de velocidad en A.','Selecciona '+(wide?'f/2':'f/4')+'.','Selecciona ISO 125.',...(wide?['En AJUSTE DE DISPARO, activa FILTRO ND.']:[]),...(flash?['Activa el flash incorporado.']:[]),'Activa la detección de cara y ojo.','Enfoca al ojo más cercano y dispara.'],tip:'El filtro ND incorporado permite usar aperturas amplias con mucha luz.'}}}
];

const app=document.querySelector('#app'),back=document.querySelector('#backBtn'),bright=document.querySelector('#brightnessBtn');
let state={screen:'home',recipe:null,answers:[],q:0,result:null,step:0};
bright.onclick=()=>{document.body.classList.toggle('light');bright.textContent=document.body.classList.contains('light')?'☀':'☾';localStorage.setItem('fuji-light',document.body.classList.contains('light')?'1':'0')};
if(localStorage.getItem('fuji-light')==='1')bright.click();
back.onclick=()=>{if(state.screen==='question'&&state.q>0){state.q--;state.answers.pop()}else if(state.screen==='steps'){state.screen='summary'}else if(state.screen==='summary'){state.screen='question';state.q=state.recipe.qs.length-1;state.answers.pop()}else state={screen:'home',recipe:null,answers:[],q:0,result:null,step:0};render()};
function render(){back.classList.toggle('hidden',state.screen==='home');if(state.screen==='home')home();if(state.screen==='question')question();if(state.screen==='summary')summary();if(state.screen==='steps')steps()}
function home(){app.innerHTML=`<h1>¿Qué foto quieres hacer?</h1><p class="lead">Elige una situación. Solo verás lo necesario.</p><section class="grid">${recipes.map((r,i)=>`<button class="card" data-i="${i}"><span class="emoji">${r.icon}</span><strong>${r.title}</strong><small>${r.desc}</small></button>`).join('')}</section>`;document.querySelectorAll('.card').forEach(b=>b.onclick=()=>{state={screen:'question',recipe:recipes[+b.dataset.i],answers:[],q:0,result:null,step:0};render()})}
function question(){const q=state.recipe.qs[state.q];app.innerHTML=`<div class="question"><div class="count">PREGUNTA ${state.q+1} DE ${state.recipe.qs.length}</div><h2>${q[0]}</h2><div class="choices">${q[1].map(v=>`<button class="choice">${v}</button>`).join('')}</div></div>`;document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{state.answers.push(b.textContent);if(state.q<state.recipe.qs.length-1)state.q++;else{state.result=state.recipe.build(state.answers);state.screen='summary'}render()})}
function summary(){app.innerHTML=`<h2>${state.recipe.icon} ${state.recipe.title}</h2><p class="lead">Estos son los ajustes de partida.</p><div class="settings">${state.result.settings.map(s=>`<div class="setting"><span>${s[0]}</span><b>${s[1]}</b></div>`).join('')}</div><button class="primary" id="start">Empezar paso a paso</button><button class="secondary" id="restart">Elegir otra situación</button><div class="tip"><b>Consejo:</b> ${state.result.tip}</div>`;document.querySelector('#start').onclick=()=>{state.screen='steps';state.step=0;render()};document.querySelector('#restart').onclick=()=>{state={screen:'home',recipe:null,answers:[],q:0,result:null,step:0};render()}}
function steps(){const total=state.result.steps.length,txt=state.result.steps[state.step];app.innerHTML=`<section class="step-shell"><div class="progress"><i style="width:${((state.step+1)/total)*100}%"></i></div><div class="step-card"><div class="step-number">PASO ${state.step+1} DE ${total}</div><div class="step-text">${txt}</div><div class="step-hint">Haz este ajuste en la cámara antes de continuar.</div></div><div class="step-actions"><button class="secondary" id="prev" ${state.step===0?'disabled':''}>Anterior</button><button class="primary" id="next">${state.step===total-1?'Finalizar':'Siguiente'}</button></div></section>`;const prev=document.querySelector('#prev');prev.onclick=()=>{if(state.step>0){state.step--;render()}};document.querySelector('#next').onclick=()=>{if(state.step<total-1){state.step++;render()}else{state.screen='summary';render()}}}
render();
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
