
let recipes=[],view="home",selected=null,answers={},qIndex=0,variant=null,step=0;
const app=document.getElementById("app"),back=document.getElementById("back"),light=document.getElementById("light");
const favs=()=>JSON.parse(localStorage.getItem("fuji-favs")||"[]"),saveFavs=x=>localStorage.setItem("fuji-favs",JSON.stringify(x));
const norm=s=>s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
fetch("recipes.json").then(r=>r.json()).then(x=>{recipes=x;renderHome()}).catch(()=>app.innerHTML='<div class="empty">No se pudieron cargar las situaciones.</div>');
light.onclick=()=>{document.documentElement.classList.toggle("light");localStorage.setItem("fuji-light",document.documentElement.classList.contains("light")?"1":"0")};
if(localStorage.getItem("fuji-light")==="1")document.documentElement.classList.add("light");
back.onclick=goBack;function header(x){back.classList.toggle("hidden",!x)}
function renderHome(filter=""){view="home";header(false);const q=norm(filter),f=favs();let list=recipes.filter(r=>!q||norm([r.title,r.summary,...r.keywords].join(" ")).includes(q));let fl=list.filter(r=>f.includes(r.id)),ol=list.filter(r=>!f.includes(r.id));
app.innerHTML=`<section class="hero home-hero"><h1>¿Qué quieres fotografiar?</h1><p>Elige una situación. Te guiaré paso a paso.</p></section><details class="search-box" ${filter?"open":""}><summary>🔎 Buscar otra situación</summary><div class="search"><input id="search" value="${esc(filter)}" placeholder="Ej.: iglesia, perro, estrellas…"></div></details>${fl.length?section("Favoritos",fl):""}${section(filter?"Resultados":"Situaciones",ol)}${!list.length?'<div class="empty">Todavía no tengo una guía para esa situación.</div>':""}`;
const search=document.getElementById("search");if(search)search.oninput=e=>renderHome(e.target.value);bind()}
function section(t,l){return `<div class="section-title"><h2>${t}</h2></div><div class="menu-list">${l.map(card).join("")}</div>`}
function card(r){const on=favs().includes(r.id);return `<article class="menu-card"><button class="menu-main" data-id="${r.id}" aria-label="Abrir ${esc(r.title)}"><span class="menu-emoji">${r.icon}</span><span class="menu-copy"><strong>${r.title}</strong><small>${r.summary}</small></span><span class="chevron">›</span></button><button class="fav ${on?"on":""}" data-fav="${r.id}" aria-label="${on?"Quitar de favoritos":"Añadir a favoritos"}">★</button></article>`}
function bind(){document.querySelectorAll(".menu-main").forEach(el=>el.onclick=()=>start(el.dataset.id));document.querySelectorAll(".fav").forEach(el=>el.onclick=e=>{e.stopPropagation();toggle(el.dataset.fav)})}
function toggle(id){let f=favs();f=f.includes(id)?f.filter(x=>x!==id):[...f,id];saveFavs(f);renderHome(document.getElementById("search")?.value||"")}
function start(id){selected=recipes.find(r=>r.id===id);answers={};qIndex=0;view="question";renderQuestion()}
function renderQuestion(){header(true);const q=selected.questions[qIndex];app.innerHTML=`<div class="panel"><div class="kicker">${selected.icon} ${selected.title}</div><h1>${q.label}</h1><div class="question-options">${q.options.map(([v,l])=>`<button class="option" data-v="${v}">${l}</button>`).join("")}</div></div>`;document.querySelectorAll(".option").forEach(b=>b.onclick=()=>{answers[q.key]=b.dataset.v;if(qIndex<selected.questions.length-1){qIndex++;renderQuestion()}else choose()})}
function choose(){variant=selected.variants[selected.questions.map(q=>answers[q.key]).join("_")]||Object.values(selected.variants)[0];view="summary";renderSummary()}
function renderSummary(){header(true);app.innerHTML=`<div class="panel"><div class="kicker">Configuración recomendada</div><h1>${selected.icon} ${selected.title}</h1><div class="settings">${variant.settings.map(x=>`<div class="setting">${x}</div>`).join("")}</div><button class="big-btn" id="begin">Empezar paso a paso</button></div>`;document.getElementById("begin").onclick=()=>{step=0;view="steps";renderStep()}}
function renderStep(){header(true);const total=variant.steps.length,pct=Math.round((step+1)/total*100);app.innerHTML=`<div class="panel step-wrap"><div class="progress-label"><span>Paso ${step+1} de ${total}</span><span>${pct}%</span></div><div class="progress"><div style="width:${pct}%"></div></div><div class="step-text">${variant.steps[step]}</div><div class="nav"><button class="big-btn secondary" id="prev">${step===0?"Ajustes":"Anterior"}</button><button class="big-btn" id="next">${step===total-1?"Checklist":"Siguiente"}</button></div></div>`;document.getElementById("prev").onclick=()=>step===0?renderSummary():(step--,renderStep());document.getElementById("next").onclick=()=>step===total-1?renderChecklist():(step++,renderStep())}
function renderChecklist(){view="check";header(true);app.innerHTML=`<div class="panel"><div class="kicker">Comprobación final</div><h1>Antes de disparar</h1><div class="checklist">${variant.checklist.map((x,i)=>`<label class="check"><input type="checkbox" data-c="${i}"><span>${x}</span></label>`).join("")}</div><div class="tip"><strong>Consejo:</strong> ${variant.tip}</div><br><button class="big-btn" id="shoot" disabled>Marca todo para continuar</button></div>`;const boxes=[...document.querySelectorAll("[data-c]")],btn=document.getElementById("shoot");boxes.forEach(x=>x.onchange=()=>{const ok=boxes.every(b=>b.checked);btn.disabled=!ok;btn.textContent=ok?"📷 DISPARA":"Marca todo para continuar"});btn.onclick=renderDone}
function renderDone(){view="done";header(true);app.innerHTML=`<div class="panel"><div class="done">📷</div><h1 style="text-align:center">¡Haz la foto!</h1><p style="text-align:center;color:var(--muted)">Configuración revisada. Ya estás preparado.</p><button class="big-btn" id="again">Volver al inicio</button></div>`;document.getElementById("again").onclick=()=>renderHome()}
function goBack(){if(view==="question"){if(qIndex>0){qIndex--;renderQuestion()}else renderHome()}else if(view==="summary"){qIndex=selected.questions.length-1;renderQuestion()}else if(view==="steps"){if(step>0){step--;renderStep()}else renderSummary()}else if(view==="check"){step=variant.steps.length-1;renderStep()}else renderHome()}
function esc(s){return s.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
if("serviceWorker" in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}))}
